In [1]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
# path to project directory
path = Path('/home/jupyter/fpl-prediction')

In [3]:
# read in training dataset
# created using fpl_data_clean notebook
train_df = pd.read_csv(path/'data/train.csv', index_col=0, dtype={'season':str})

In [4]:
train_df.tail()

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,season,play_proba
77805,Grant_Hanley,18,2,90,Norwich,Wolverhampton Wanderers,0.295212,0.746215,True,0,1920,0.50
77806,Roberto_Pereyra,18,3,13,Watford,Manchester United,0.433797,1.560524,True,1,1920,0.75
77807,Sead_Kolasinac,18,2,0,Arsenal,Everton,1.413491,1.033814,False,0,1920,0.75
77808,Stuart_Armstrong,18,3,75,Southampton,Aston Villa,0.469252,0.522434,False,2,1920,1.00
77809,Rúben Diogo_da Silva Neves,18,3,90,Wolverhampton Wanderers,Norwich,0.746215,0.295212,False,2,1920,1.00

In [21]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77290 entries, 0 to 77289
Data columns (total 12 columns):
player                                 77290 non-null object
gw                                     77290 non-null int64
position                               77290 non-null int64
minutes                                77290 non-null int64
team                                   77290 non-null object
opponent_team                          77290 non-null object
relative_market_value_team             77290 non-null float64
relative_market_value_opponent_team    77290 non-null float64
was_home                               77290 non-null bool
total_points                           77290 non-null int64
season                                 77290 non-null object
play_proba                             9289 non-null float64
dtypes: bool(1), float64(3), int64(4), object(4)
memory usage: 7.1+ MB

In [38]:
X, y = train_df.iloc[:,[1,2,3,4,5,6,7,8,10,11]], train_df.iloc[:,9]

In [39]:
# set categorical and continuous variables
cat_vars = ['gw', 'position', 'team', 'opponent_team', 'was_home', 'season']
cont_vars = ['minutes', 'relative_market_value_team', 'relative_market_value_opponent_team']

In [52]:
# encode string input values as integers
encoded_x = None
for var in cat_vars:
    label_encoder = LabelEncoder()
    feature = label_encoder.fit_transform(X.loc[:,var])
    feature = feature.reshape(X.shape[0], 1)
    onehot_encoder = OneHotEncoder(sparse=False, categories='auto')
    feature = onehot_encoder.fit_transform(feature)
    if encoded_x is None:
        encoded_x = feature
    else:
        encoded_x = np.concatenate((encoded_x, feature), axis=1)
print("X shape: : ", encoded_x.shape)

X shape: :  (77290, 106)

In [56]:
X

,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,season,play_proba
0,1,2,0,West Ham United,Chelsea,0.895471,2.243698,False,1617,NaN
1,1,3,15,Everton,Tottenham Hotspur,1.057509,1.433690,True,1617,NaN
2,1,3,60,Arsenal,Liverpool,1.944129,1.465860,True,1617,NaN
3,1,3,0,Watford,Southampton,0.704200,0.796805,False,1617,NaN
4,1,2,0,Chelsea,West Ham United,2.243698,0.895471,True,1617,NaN
5,1,4,90,Hull City,Leicester City,0.494447,0.650832,True,1617,NaN
6,1,4,90,Hull City,Leicester City,0.494447,0.650832,True,1617,NaN
7,1,3,90,Middlesbrough,Stoke City,0.452793,0.718705,True,1617,NaN
8,1,1,0,Bournemouth,Manchester United,0.384921,1.983179,True,1617,NaN
9,1,3,69,Middlesbrough,Stoke City,0.452793,0.718705,True,1617,NaN
10,1,3,75,Liverpool,Arsenal,1.465860,1.944129,False,1617,NaN
11,1,2,0,Sunderland,Manchester City,0.418392,2.311012,False,1617,NaN
12,1,3,0,Middlesbrough,Stoke City,0.452793,0.718705,True,1617,NaN
13,1,2,90,Bournemouth,Manchester United,0.384921,1.983179,True,1617,NaN
14,1,3,72,Middlesbrough,Southampton,0.452793,0.796805,False,1617,NaN
15,1,3,27,Sunderland,Manchester City,0.418392,2.311012,False,1617,NaN
16,1,1,90,West Ham United,Chelsea,0.895471,2.243698,False,1617,NaN
17,1,3,90,Hull City,Leicester City,0.494447,0.650832,True,1617,NaN
18,1,4,90,Leicester City,Hull City,0.650832,0.494447,False,1617,NaN
19,1,2,90,Liverpool,Arsenal,1.465860,1.944129,False,1617,NaN
20,1,3,90,Middlesbrough,Stoke City,0.452793,0.718705,True,1617,NaN
21,1,2,90,Manchester City,Sunderland,2.311012,0.418392,True,1617,NaN
22,1,1,0,Liverpool,Arsenal,1.465860,1.944129,False,1617,NaN
23,1,3,90,Arsenal,Liverpool,1.944129,1.465860,True,1617,NaN
24,1,2,0,Middlesbrough,Stoke City,0.452793,0.718705,True,1617,NaN
25,1,2,0,Hull City,Leicester City,0.494447,0.650832,True,1617,NaN
26,1,3,58,Arsenal,Liverpool,1.944129,1.465860,True,1617,NaN
27,1,1,0,Southampton,Watford,0.796805,0.704200,True,1617,NaN
28,1,3,32,Arsenal,Liverpool,1.944129,1.465860,True,1617,NaN
29,1,3,0,Tottenham Hotspur,Everton,1.433690,1.057509,False,1617,NaN
...,...,...,...,...,...,...,...,...,...,...
77260,17,4,90,Newcastle United,Burnley,0.561705,0.406164,False,1920,1.00
77261,17,1,90,Arsenal,Manchester City,1.413491,2.711234,True,1920,1.00
77262,17,2,90,Crystal Palace,Brighton and Hove Albion,0.464142,0.453089,True,1920,1.00
77263,17,3,90,Liverpool,Watford,2.460966,0.433797,True,1920,1.00
77264,17,4,0,Southampton,West Ham United,0.469252,0.699185,True,1920,0.00
77265,17,3,58,Liverpool,Watford,2.460966,0.433797,True,1920,1.00
77266,17,2,90,Wolverhampton Wanderers,Tottenham Hotspur,0.746215,2.001099,True,1920,1.00
77267,17,3,90,Wolverhampton Wanderers,Tottenham Hotspur,0.746215,2.001099,True,1920,1.00
77268,17,3,0,Wolverhampton Wanderers,Tottenham Hotspur,0.746215,2.001099,True,1920,0.00
77269,17,4,0,Bournemouth,Chelsea,0.713784,1.757609,False,1920,0.00
77270,17,4,90,Arsenal,Manchester City,1.413491,2.711234,True,1920,1.00
77271,17,3,0,Wolverhampton Wanderers,Tottenham Hotspur,0.746215,2.001099,True,1920,0.00
77272,17,3,50,Arsenal,Manchester City,1.413491,2.711234,True,1920,1.00
77273,17,2,0,Burnley,Newcastle United,0.406164,0.561705,True,1920,0.25
77274,17,3,0,Tottenham Hotspur,Wolverhampton Wanderers,2.001099,0.746215,False,1920,0.00
77275,17,3,90,Bournemouth,Chelsea,0.713784,1.757609,False,1920,1.00
77276,17,3,70,Everton,Manchester United,1.033814,1.560524,False,1920,1.00
77277,17,3,90,Burnley,Newcastle United,0.406164,0.561705,True,1920,1.00
77278,17,3,90,Aston Villa,Sheffield United,0.522434,0.242030,False,1920,1.00
77279,17,1,0,Watford,Liverpool,0.433797,2.460966,False,1920,1.00
77280,17,1,0,Southampton,West Ham United,0.469252,0.699185,True,1920,0.00
77281,17,4,0,Norwich,Leicester City,0.295212,1.054253,False,1920,0.00
77282,17,2,0,Manchester United,Everton,1.560524,1.033814,True,1920,0.00
77283,17,2,0,Aston Villa,Sheffield United,0.522434,0.242030,False,1920,1.00
77284,17,3,90,Crystal Palace,Brighton and Hove Albion,0.464142,0.453089,True,1920,1.00
77285,17,3,90,Crystal Palace,Brighton and Hove Albion,0.464142,0.453089,True,1920,1.00
77286,17,2,90,Everton,Manchester United,1.033814,1.560524,False,1920,1.00
77287,17,3,45,Crystal Palace,Brighton and Hove Albion,0.464142,0.453089,True,1920,1.00
77288,17,3,90,Brighton and Hove Albion,Crystal Palace,0.453089,0.464142,False,1920,1.00
77289,17,1,0,Wolverhampton Wanderers,Tottenham Hotspur,0.746215,2.001099,True,1920,1.00

In [63]:
X.loc[:,cont_vars]

,minutes,relative_market_value_team,relative_market_value_opponent_team
0,0,0.895471,2.243698
1,15,1.057509,1.433690
2,60,1.944129,1.465860
3,0,0.704200,0.796805
4,0,2.243698,0.895471
5,90,0.494447,0.650832
6,90,0.494447,0.650832
7,90,0.452793,0.718705
8,0,0.384921,1.983179
9,69,0.452793,0.718705
10,75,1.465860,1.944129
11,0,0.418392,2.311012
12,0,0.452793,0.718705
13,90,0.384921,1.983179
14,72,0.452793,0.796805
15,27,0.418392,2.311012
16,90,0.895471,2.243698
17,90,0.494447,0.650832
18,90,0.650832,0.494447
19,90,1.465860,1.944129
20,90,0.452793,0.718705
21,90,2.311012,0.418392
22,0,1.465860,1.944129
23,90,1.944129,1.465860
24,0,0.452793,0.718705
25,0,0.494447,0.650832
26,58,1.944129,1.465860
27,0,0.796805,0.704200
28,32,1.944129,1.465860
29,0,1.433690,1.057509
...,...,...,...
77260,90,0.561705,0.406164
77261,90,1.413491,2.711234
77262,90,0.464142,0.453089
77263,90,2.460966,0.433797
77264,0,0.469252,0.699185
77265,58,2.460966,0.433797
77266,90,0.746215,2.001099
77267,90,0.746215,2.001099
77268,0,0.746215,2.001099
77269,0,0.713784,1.757609
77270,90,1.413491,2.711234
77271,0,0.746215,2.001099
77272,50,1.413491,2.711234
77273,0,0.406164,0.561705
77274,0,2.001099,0.746215
77275,90,0.713784,1.757609
77276,70,1.033814,1.560524
77277,90,0.406164,0.561705
77278,90,0.522434,0.242030
77279,0,0.433797,2.460966
77280,0,0.469252,0.699185
77281,0,0.295212,1.054253
77282,0,1.560524,1.033814
77283,0,0.522434,0.242030
77284,90,0.464142,0.453089
77285,90,0.464142,0.453089
77286,90,1.033814,1.560524
77287,45,0.464142,0.453089
77288,90,0.453089,0.464142
77289,0,0.746215,2.001099