In [1]:
# import required libriaries
from pathlib import Path
from helpers import *

In [2]:
# path to data directory
path = Path('/home/jupyter/fpl-prediction/data')

In [3]:
# read in latest training set
df_train = pd.read_csv(path/'train.csv', index_col=0, dtype={'season':str})

# path to current season
season_paths = [path/'2019-20']

# name for current season
season_names = ['1920']

# team codes
teams = pd.read_csv(path/'teams.csv')

# latest remaining season dataset, for latest week's play_proba values
remaining_season = pd.read_csv(path/'remaining_season.csv', index_col=0)

# create players dataset
all_players = build_players(path, season_paths, season_names, teams)

# 2019-20 market value
# table was in slightly different position for 2019-20 season
# should check that 2019-20 season values remain the same once season starts
teams_mv = build_season_mv('1920', 11, range(13,33))

In [5]:
df_train.tail()

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,season,play_proba
68457,Yoshinori_Muto,1,4,0,Newcastle United,Arsenal,0.542356,1.448866,True,0,1920,1.0
68458,Youri_Tielemans,1,3,90,Leicester City,Wolverhampton Wanderers,0.886283,0.673382,True,3,1920,1.0
68459,Yves_Bissouma,1,3,0,Brighton and Hove Albion,Watford,0.476156,0.555819,False,0,1920,0.0
68460,Çaglar_Söyüncü,1,2,90,Leicester City,Wolverhampton Wanderers,0.886283,0.673382,True,6,1920,1.0
68461,Ørjan_Nyland,1,1,0,Aston Villa,Tottenham Hotspur,0.338194,2.113981,False,0,1920,1.0

In [6]:
# find the latest gameweek
last_gw = df_train['gw'][df_train['season'] == '1920'].max()

if np.isnan(last_gw): 
    last_gw = 1 
else: 
    last_gw = last_gw + 1
    
last_gw

2

In [7]:
# build training set for latest gameweek
df_latest = build_season(season_paths[0], season_names[0], all_players, teams, teams_mv, [last_gw])

In [8]:
df_latest

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,season
0,Aaron_Cresswell,2,2,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920
1,Aaron_Lennon,2,3,18,Burnley,Arsenal,0.442049,1.449683,False,1,1920
2,Aaron_Mooy,2,3,5,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,1,1920
3,Aaron_Ramsdale,2,1,90,Bournemouth,Aston Villa,0.687512,0.338385,False,4,1920
4,Aaron_Wan-Bissaka,2,2,90,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,1,1920
5,Abdoulaye_Doucouré,2,3,90,Watford,Everton,0.556133,1.125801,False,2,1920
6,Adama_Traoré,2,3,45,Wolverhampton Wanderers,Manchester United,0.673762,1.680644,True,1,1920
7,Adam_Lallana,2,3,0,Liverpool,Southampton,2.298868,0.624562,False,0,1920
8,Adam_Masina,2,2,0,Watford,Everton,0.556133,1.125801,False,0,1920
9,Adam_Smith,2,2,90,Bournemouth,Aston Villa,0.687512,0.338385,False,2,1920
10,Adam_Webster,2,2,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920
11,Ademola_Lookman,2,3,0,Everton,Watford,1.125801,0.556133,True,0,1920
12,Adrian_Mariappa,2,2,0,Watford,Everton,0.556133,1.125801,False,0,1920
13,Adrián_San Miguel del Castillo,2,1,90,Liverpool,Southampton,2.298868,0.624562,False,3,1920
14,Ahmed_El Mohamady,2,2,90,Aston Villa,Bournemouth,0.338385,0.687512,True,4,1920
15,Ainsley_Maitland-Niles,2,2,90,Arsenal,Burnley,1.449683,0.442049,True,2,1920
16,Albian_Ajeti,2,4,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920
17,Alexander_Tettey,2,3,3,Norwich,Newcastle United,0.197875,0.542662,True,1,1920
18,Alexandre Nascimento_Costa Silva,2,4,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920
19,Alexandre_Lacazette,2,4,70,Arsenal,Burnley,1.449683,0.442049,True,8,1920
20,Alexis_Sánchez,2,3,0,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,0,1920
21,Alex_Iwobi,2,3,0,Everton,Watford,1.125801,0.556133,True,0,1920
22,Alex_McCarthy,2,1,0,Southampton,Liverpool,0.624562,2.298868,True,0,1920
23,Alex_Oxlade-Chamberlain,2,3,88,Liverpool,Southampton,2.298868,0.624562,False,2,1920
24,Alireza_Jahanbakhsh,2,3,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920
25,Alisson_Ramses Becker,2,1,0,Liverpool,Southampton,2.298868,0.624562,False,0,1920
26,Allan_Saint-Maximin,2,3,0,Newcastle United,Norwich,0.542662,0.197875,False,0,1920
27,Andreas_Christensen,2,2,90,Chelsea,Leicester City,1.799885,0.881412,True,2,1920
28,Andreas_Pereira,2,3,1,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,1,1920
29,Andrew_Robertson,2,2,90,Liverpool,Southampton,2.298868,0.624562,False,2,1920
...,...,...,...,...,...,...,...,...,...,...,...
499,Troy_Deeney,2,4,90,Watford,Everton,0.556133,1.125801,False,2,1920
500,Troy_Parrott,2,4,0,Tottenham Hotspur,Manchester City,2.115173,2.728563,False,0,1920
501,Tyreke_Johnson,2,3,0,Southampton,Liverpool,0.624562,2.298868,True,0,1920
502,Tyrone_Mings,2,2,90,Aston Villa,Bournemouth,0.338385,0.687512,True,1,1920
503,Vicente_Guaita,2,1,90,Crystal Palace,Sheffield United,0.495653,0.150715,False,2,1920
504,Victor_Lindelöf,2,2,90,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,2,1920
505,Victor_Wanyama,2,3,0,Tottenham Hotspur,Manchester City,2.115173,2.728563,False,0,1920
506,Vincent_Janssen,2,4,0,Tottenham Hotspur,Manchester City,2.115173,2.728563,False,0,1920
507,Virgil_van Dijk,2,2,90,Liverpool,Southampton,2.298868,0.624562,False,2,1920
508,Víctor_Camarasa,2,3,0,Crystal Palace,Sheffield United,0.495653,0.150715,False,0,1920
509,Wayne_Hennessey,2,1,0,Crystal Palace,Sheffield United,0.495653,0.150715,False,0,1920
510,Wesley_Hoedt,2,2,0,Southampton,Liverpool,0.624562,2.298868,True,0,1920
511,Wesley_Moraes,2,4,90,Aston Villa,Bournemouth,0.338385,0.687512,True,2,1920
512,Wes_Morgan,2,2,0,Leicester City,Chelsea,0.881412,1.799885,False,0,1920
513,Wilfred_Ndidi,2,3,90,Leicester City,Chelsea,0.881412,1.799885,False,10,1920
514,Wilfried_Zaha,2,3,90,Crystal Palace,Sheffield United,0.495653,0.150715,False,2,1920
515,Willian_Borges Da Silva,2,3,19,Chelsea,Leicester City,1.799885,0.881412,True,1,1920
516,Willy_Boly,2,2,90,Wolverhampton Wanderers,Manchester United,0.673762,1.680644,True,2,1920
517,Willy_Caballero,2,1,0,Chelsea,Leicester City,1.799885,0.881412,True,0,1920
518,Will_Hughes,2,3,66,Watford,Everton,0.556133,1.125801,False,2,1920
519,Will_Norris,2,1,0,Wolverhampton Wanderers,Manchester United,0.673762,1.680644,True,0,1920
520,Winston_Reid,2,2,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920
521,Xherdan_Shaqiri,2,3,0,Liverpool,Southampton,2.298868,0.624562,False,0,1920
522,Yan_Valery,2,2,90,Southampton,Liverpool,0.624562,2.298868,True,1,1920
523,Yerry_Mina,2,2,90,Everton,Watford,1.125801,0.556133,True,7,1920
524,Yoshinori_Muto,2,4,23,Newcastle United,Norwich,0.542662,0.197875,False,1,1920
525,Youri_Tielemans,2,3,90,Leicester City,Chelsea,0.881412,1.799885,False,2,1920
526,Yves_Bissouma,2,3,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920
527,Çaglar_Söyüncü,2,2,90,Leicester City,Chelsea,0.881412,1.799885,False,2,1920
528,Ørjan_Nyland,2,1,0,Aston Villa,Bournemouth,0.338385,0.687512,True,0,1920

In [9]:
df_latest.shape

(529, 11)

In [10]:
last_play_proba = remaining_season[remaining_season['gw'] == last_gw][['player', 'play_proba']]

In [11]:
last_play_proba.head()

                      player  play_proba
0           Shkodran_Mustafi        1.00
1            Héctor_Bellerín        0.00
2             Sead_Kolasinac        0.25
3     Ainsley_Maitland-Niles        1.00
4  Sokratis_Papastathopoulos        1.00

In [12]:
# add latest week's play_proba for each player
df_latest = df_latest.merge(last_play_proba, on='player', how='left')

In [13]:
df_latest

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,season,play_proba
0,Aaron_Cresswell,2,2,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920,1.00
1,Aaron_Lennon,2,3,18,Burnley,Arsenal,0.442049,1.449683,False,1,1920,1.00
2,Aaron_Mooy,2,3,5,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,1,1920,1.00
3,Aaron_Ramsdale,2,1,90,Bournemouth,Aston Villa,0.687512,0.338385,False,4,1920,1.00
4,Aaron_Wan-Bissaka,2,2,90,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,1,1920,1.00
5,Abdoulaye_Doucouré,2,3,90,Watford,Everton,0.556133,1.125801,False,2,1920,1.00
6,Adama_Traoré,2,3,45,Wolverhampton Wanderers,Manchester United,0.673762,1.680644,True,1,1920,1.00
7,Adam_Lallana,2,3,0,Liverpool,Southampton,2.298868,0.624562,False,0,1920,1.00
8,Adam_Masina,2,2,0,Watford,Everton,0.556133,1.125801,False,0,1920,1.00
9,Adam_Smith,2,2,90,Bournemouth,Aston Villa,0.687512,0.338385,False,2,1920,1.00
10,Adam_Webster,2,2,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920,1.00
11,Ademola_Lookman,2,3,0,Everton,Watford,1.125801,0.556133,True,0,1920,0.00
12,Adrian_Mariappa,2,2,0,Watford,Everton,0.556133,1.125801,False,0,1920,1.00
13,Adrián_San Miguel del Castillo,2,1,90,Liverpool,Southampton,2.298868,0.624562,False,3,1920,1.00
14,Ahmed_El Mohamady,2,2,90,Aston Villa,Bournemouth,0.338385,0.687512,True,4,1920,1.00
15,Ainsley_Maitland-Niles,2,2,90,Arsenal,Burnley,1.449683,0.442049,True,2,1920,1.00
16,Albian_Ajeti,2,4,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920,1.00
17,Alexander_Tettey,2,3,3,Norwich,Newcastle United,0.197875,0.542662,True,1,1920,0.00
18,Alexandre Nascimento_Costa Silva,2,4,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920,1.00
19,Alexandre_Lacazette,2,4,70,Arsenal,Burnley,1.449683,0.442049,True,8,1920,1.00
20,Alexis_Sánchez,2,3,0,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,0,1920,0.75
21,Alex_Iwobi,2,3,0,Everton,Watford,1.125801,0.556133,True,0,1920,1.00
22,Alex_McCarthy,2,1,0,Southampton,Liverpool,0.624562,2.298868,True,0,1920,1.00
23,Alex_Oxlade-Chamberlain,2,3,88,Liverpool,Southampton,2.298868,0.624562,False,2,1920,1.00
24,Alireza_Jahanbakhsh,2,3,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920,1.00
25,Alisson_Ramses Becker,2,1,0,Liverpool,Southampton,2.298868,0.624562,False,0,1920,0.75
26,Allan_Saint-Maximin,2,3,0,Newcastle United,Norwich,0.542662,0.197875,False,0,1920,1.00
27,Andreas_Christensen,2,2,90,Chelsea,Leicester City,1.799885,0.881412,True,2,1920,1.00
28,Andreas_Pereira,2,3,1,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,1,1920,1.00
29,Andrew_Robertson,2,2,90,Liverpool,Southampton,2.298868,0.624562,False,2,1920,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...
499,Troy_Deeney,2,4,90,Watford,Everton,0.556133,1.125801,False,2,1920,1.00
500,Troy_Parrott,2,4,0,Tottenham Hotspur,Manchester City,2.115173,2.728563,False,0,1920,1.00
501,Tyreke_Johnson,2,3,0,Southampton,Liverpool,0.624562,2.298868,True,0,1920,0.00
502,Tyrone_Mings,2,2,90,Aston Villa,Bournemouth,0.338385,0.687512,True,1,1920,1.00
503,Vicente_Guaita,2,1,90,Crystal Palace,Sheffield United,0.495653,0.150715,False,2,1920,1.00
504,Victor_Lindelöf,2,2,90,Manchester United,Wolverhampton Wanderers,1.680644,0.673762,False,2,1920,1.00
505,Victor_Wanyama,2,3,0,Tottenham Hotspur,Manchester City,2.115173,2.728563,False,0,1920,1.00
506,Vincent_Janssen,2,4,0,Tottenham Hotspur,Manchester City,2.115173,2.728563,False,0,1920,0.00
507,Virgil_van Dijk,2,2,90,Liverpool,Southampton,2.298868,0.624562,False,2,1920,1.00
508,Víctor_Camarasa,2,3,0,Crystal Palace,Sheffield United,0.495653,0.150715,False,0,1920,1.00
509,Wayne_Hennessey,2,1,0,Crystal Palace,Sheffield United,0.495653,0.150715,False,0,1920,1.00
510,Wesley_Hoedt,2,2,0,Southampton,Liverpool,0.624562,2.298868,True,0,1920,1.00
511,Wesley_Moraes,2,4,90,Aston Villa,Bournemouth,0.338385,0.687512,True,2,1920,1.00
512,Wes_Morgan,2,2,0,Leicester City,Chelsea,0.881412,1.799885,False,0,1920,1.00
513,Wilfred_Ndidi,2,3,90,Leicester City,Chelsea,0.881412,1.799885,False,10,1920,1.00
514,Wilfried_Zaha,2,3,90,Crystal Palace,Sheffield United,0.495653,0.150715,False,2,1920,1.00
515,Willian_Borges Da Silva,2,3,19,Chelsea,Leicester City,1.799885,0.881412,True,1,1920,0.50
516,Willy_Boly,2,2,90,Wolverhampton Wanderers,Manchester United,0.673762,1.680644,True,2,1920,1.00
517,Willy_Caballero,2,1,0,Chelsea,Leicester City,1.799885,0.881412,True,0,1920,1.00
518,Will_Hughes,2,3,66,Watford,Everton,0.556133,1.125801,False,2,1920,1.00
519,Will_Norris,2,1,0,Wolverhampton Wanderers,Manchester United,0.673762,1.680644,True,0,1920,0.00
520,Winston_Reid,2,2,0,West Ham United,Brighton and Hove Albion,0.739612,0.471053,False,0,1920,1.00
521,Xherdan_Shaqiri,2,3,0,Liverpool,Southampton,2.298868,0.624562,False,0,1920,1.00
522,Yan_Valery,2,2,90,Southampton,Liverpool,0.624562,2.298868,True,1,1920,1.00
523,Yerry_Mina,2,2,90,Everton,Watford,1.125801,0.556133,True,7,1920,1.00
524,Yoshinori_Muto,2,4,23,Newcastle United,Norwich,0.542662,0.197875,False,1,1920,1.00
525,Youri_Tielemans,2,3,90,Leicester City,Chelsea,0.881412,1.799885,False,2,1920,1.00
526,Yves_Bissouma,2,3,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920,0.00
527,Çaglar_Söyüncü,2,2,90,Leicester City,Chelsea,0.881412,1.799885,False,2,1920,1.00
528,Ørjan_Nyland,2,1,0,Aston Villa,Bournemouth,0.338385,0.687512,True,0,1920,1.00

In [14]:
df_train_new = pd.concat([df_train, df_latest], ignore_index=True, axis=0)

In [15]:
df_train_new.tail()

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,season,play_proba
68986,Yoshinori_Muto,2,4,23,Newcastle United,Norwich,0.542662,0.197875,False,1,1920,1.0
68987,Youri_Tielemans,2,3,90,Leicester City,Chelsea,0.881412,1.799885,False,2,1920,1.0
68988,Yves_Bissouma,2,3,0,Brighton and Hove Albion,West Ham United,0.471053,0.739612,True,0,1920,0.0
68989,Çaglar_Söyüncü,2,2,90,Leicester City,Chelsea,0.881412,1.799885,False,2,1920,1.0
68990,Ørjan_Nyland,2,1,0,Aston Villa,Bournemouth,0.338385,0.687512,True,0,1920,1.0

In [16]:
# save latest training set to csv
# overwrite existing one
df_train_new.to_csv(path/'train.csv')

In [17]:
## now need to create the prediction set
# start by reading fixtures.csv
# set starting gameweek (where are we right now in the season)
current_gw = last_gw + 1
fixtures = pd.read_csv(path/'fixtures.csv')
fixtures = fixtures[fixtures['gw'] >= current_gw]

In [18]:
fixtures.head(10)

                   home_team         away_team  gw
20               Aston Villa           Everton   3
21                   Norwich           Chelsea   3
22  Brighton and Hove Albion       Southampton   3
23         Manchester United    Crystal Palace   3
24          Sheffield United    Leicester City   3
25                   Watford   West Ham United   3
26   Wolverhampton Wanderers           Burnley   3
27                 Liverpool           Arsenal   3
28               Bournemouth   Manchester City   3
29         Tottenham Hotspur  Newcastle United   3

In [19]:
# add team codes for home and away teams
fixtures = fixtures.merge(teams, left_on='home_team', right_on='team', how='left')
fixtures = fixtures.merge(teams, left_on='away_team', right_on='team', how='left')
fixtures = fixtures[['gw', 'home_team', 'away_team', 'team_code_x', 'team_code_y']]
fixtures.rename(index=str,
                columns={'team_code_x':'home_team_code',
                         'team_code_y':'away_team_code'},
                inplace=True)

In [20]:
fixtures.head()

,gw,home_team,away_team,home_team_code,away_team_code
0,3,Aston Villa,Everton,7,11
1,3,Norwich,Chelsea,45,8
2,3,Brighton and Hove Albion,Southampton,36,20
3,3,Manchester United,Crystal Palace,1,31
4,3,Sheffield United,Leicester City,49,13

In [21]:
# join home team to all players for current season
home_df = fixtures.merge(all_players, 
               left_on='home_team_code', 
               right_on='team_1920', 
               how='left')

# pull out the required fields and rename columns
home_df = home_df[['gw', 'home_team', 'away_team', 'full_name', 'position_1920', 'cost_1920', 'play_proba_1920']]
home_df.rename(index=str, 
               columns={'home_team':'team',
                        'away_team':'opponent_team',
                        'full_name':'player',
                        'position_1920':'position',
                        'cost_1920':'price',
                        'play_proba_1920':'play_proba'},
              inplace=True)

# add home flag
home_df['was_home'] = True

In [22]:
# join away team to all players for current season
away_df = fixtures.merge(all_players, 
               left_on='away_team_code', 
               right_on='team_1920', 
               how='left')

# pull out the required fields and rename columns
away_df = away_df[['gw',  'away_team', 'home_team', 'full_name', 'position_1920', 'cost_1920', 'play_proba_1920']]
away_df.rename(index=str, 
               columns={'away_team':'team',
                        'home_team':'opponent_team',
                        'full_name':'player',
                        'position_1920':'position',
                        'cost_1920':'price',
                        'play_proba_1920':'play_proba'},
              inplace=True)

# add home flag
away_df['was_home'] = False

In [23]:
# look at away players
away_df.head()

,gw,team,opponent_team,player,position,price,play_proba,was_home
0,3,Everton,Aston Villa,Alex_Iwobi,3,59,None,False
1,3,Everton,Aston Villa,Lucas_Digne,2,60,75,False
2,3,Everton,Aston Villa,Yerry_Mina,2,55,None,False
3,3,Everton,Aston Villa,Michael_Keane,2,55,None,False
4,3,Everton,Aston Villa,Seamus_Coleman,2,55,None,False

In [24]:
# look at home players
home_df.head()

,gw,team,opponent_team,player,position,price,play_proba,was_home
0,3,Aston Villa,Everton,Ahmed_El Mohamady,2,45,None,True
1,3,Aston Villa,Everton,James_Chester,2,45,0,True
2,3,Aston Villa,Everton,Neil_Taylor,2,45,None,True
3,3,Aston Villa,Everton,Kortney_Hause,2,45,0,True
4,3,Aston Villa,Everton,Jonathan_Kodjia,4,55,0,True

In [25]:
# concatenate home and away players
remaining_season_df = home_df.append(away_df).reset_index(drop=True)

# add home and away team market values
remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '1920'],
                                                left_on='team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '1920'],
                                                left_on='opponent_team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df.rename(index=str, 
                           columns={'relative_market_value_x':'relative_market_value_team',
                                    'relative_market_value_y':'relative_market_value_opponent_team'},
                           inplace=True)

# add season name
remaining_season_df['season'] = '1920'

# divide cost by 10 for actual cost
remaining_season_df['price'] = remaining_season_df['price']/10

# set availability probability
# 0 = 0% chance, 25 = 25% chance, etc
# 'None' or '100' = 100% chance
remaining_season_df.loc[remaining_season_df['play_proba'] == 'None', 'play_proba'] = 100
remaining_season_df['play_proba'] = remaining_season_df['play_proba'].astype('float') / 100

# set minutes equal to 90 multiplied by their play probabiliby for all players, for now
remaining_season_df['minutes'] = 90 * remaining_season_df['play_proba']

# cast position to integer
remaining_season_df['position'] = remaining_season_df['position'].astype(int)

In [26]:
remaining_season_df.head()

,gw,team,opponent_team,player,position,price,play_proba,was_home,relative_market_value_team,relative_market_value_opponent_team,season,minutes
0,3,Aston Villa,Everton,Ahmed_El Mohamady,2,4.5,1.0,True,0.338385,1.125801,1920,90.0
1,3,Aston Villa,Everton,James_Chester,2,4.5,0.0,True,0.338385,1.125801,1920,0.0
2,3,Aston Villa,Everton,Neil_Taylor,2,4.5,1.0,True,0.338385,1.125801,1920,90.0
3,3,Aston Villa,Everton,Kortney_Hause,2,4.5,0.0,True,0.338385,1.125801,1920,0.0
4,3,Aston Villa,Everton,Jonathan_Kodjia,4,5.5,0.0,True,0.338385,1.125801,1920,0.0

In [27]:
# save latest prediction set to csv
remaining_season_df.to_csv(path/'remaining_season.csv')